const items =[
    {
      id:1,
      Details_of_the_Standard:"Std. Resistors 0.01Ω to 1MΩ",
      Model_and_Make: " 1440, Series, GR ",
      Details_Of_the_Traceability:  "ETDC(Hyd)",
      Calibration_date: "06-02-2024",
      Calibration_Due_date: "06-02-2025",

    },
    {
      id:2,
      Details_of_the_Standard:"Std. Resistors 0.001Ω",
      Model_and_Make: "9409, Vaiseshika",
      Details_Of_the_Traceability:  "ETDC(Hyd)",
      Calibration_date: "06-02-2024",
      Calibration_Due_date: "06-02-2025",
    },
    {
      id:3, 
      Details_of_the_Standard:  "Std. Resistors 10uΩ,100uΩ, 0.001Ω" ,
      Model_and_Make: "9334A, Guildline",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "13-11-2023",
      Calibration_Due_date: "13-11-2024",
    },
    {
      id:4, 
      Details_of_the_Standard:  "Std. Resistors 0.1Ω to1MΩ",
      Model_and_Make: "SRX Series, IET",
      Details_Of_the_Traceability:  "ETDC(Bg)" ,
      Calibration_date: "13-11-2023",
      Calibration_Due_date: "13-11-2024",
    },
    {
      id:5, 
      Details_of_the_Standard:  "Std. Resistors",
      Model_and_Make: "742A-1 & 10k. Fluke",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "13-11-2023",
      Calibration_Due_date: "13-11-2024",     
    },
    {
      id:6, 
      Details_of_the_Standard:   "STD. Resistors (High Voltage)",
      Model_and_Make: "SRC Series,IET",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "13-11-2023",
      Calibration_Due_date: "13-11-2024",
    },
    {
      id: 7,
      Details_of_the_Standard:"Standard Inductors",
      Model_and_Make: "1482, Series, GR",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "03-11-2023",
      Calibration_Due_date: "03-11-2024",
    },
    {
      id: 8,
      Details_of_the_Standard:  "Decade Inductance Box" ,
      Model_and_Make: "1491G, GR",
      Details_Of_the_Traceability: "ETDC(Bg)" ,
      Calibration_date: "03-11-2023",
      Calibration_Due_date: "03-11-2024",
    },
    {
      id: 9,
      Details_of_the_Standard:  "Standard Capacitors" ,
      Model_and_Make: "1409, Series, GR" ,
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "15-11-2023",
      Calibration_Due_date: "15-11-2024",
    },
    {
      id: 10,
      Details_of_the_Standard:  "Standard Capacitors" ,
      Model_and_Make: "505 Series, GR",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "15-11-2023",
      Calibration_Due_date: "15-11-2024",
    },
    {
      id: 11,
      Details_of_the_Standard:  "Standard Capacitors" ,
      Model_and_Make: "SC Series, IET" ,
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "15-11-2023",
      Calibration_Due_date: "15-11-2024",
    },
    {
      id: 12,
      Details_of_the_Standard:  "High Stability Mega Ohm DRB" ,
      Model_and_Make: "8400, Vaiseshika",
      Details_Of_the_Traceability: "ETDC(Hyd)" ,
      Calibration_date: "24-01-2023",
      Calibration_Due_date: "24-01-2024",
    },
    {
      id: 13,
      Details_of_the_Standard: "High precision Calibrator with Current Amplifier"  ,
      Model_and_Make: "5720A & 5725A,Fluke",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "21-11-2023",
      Calibration_Due_date: "21-11-2024",
    },
    {id: 14,
        Details_of_the_Standard: "Multi function Calibrator with Oscilloscope Calibrator."  ,
        Model_and_Make: "9100,Fluke ",
        Details_Of_the_Traceability:  "ETDC(Bg) ",
        Calibration_date: "11-09-2024 ",
        Calibration_Due_date: "11-09-2025 ",
    },    
    {id: 14,
        Details_of_the_Standard: "Current Coil"  ,
        Model_and_Make: "X50,X10, Fluke",
        Details_Of_the_Traceability:  "ETDC(Bg)",
        Calibration_date: "08-11-2023",
        Calibration_Due_date: "08-11-2024",
    },
    {
      id: 15,
      Details_of_the_Standard:  "Calibrator with Oscilloscope Calibrator." ,
      Model_and_Make: "5520A, Fluke",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "09-11-2023 ",
      Calibration_Due_date:"09-11-2024" ,
    },
    {
      id: 15,
      Details_of_the_Standard:  "Current Coil" ,
      Model_and_Make: "5500A, Fluke",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "07-11-2023",
      Calibration_Due_date:"07-11-2024" ,
    },
    {
      id: 16,
      Details_of_the_Standard:   "Oscilloscope Calibrator",
      Model_and_Make: "5820A, Fluke",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "15-11-2023",
      Calibration_Due_date: "15-11-2024",
    },
    {
      id: 17,
      Details_of_the_Standard:   "DMM 8½  Lab Std.",
      Model_and_Make: "8508A, Fluke",
      Details_Of_the_Traceability:  "ETDC(Bg)",
      Calibration_date: "21-11-2023",
      Calibration_Due_date: "21-11-2024",
    },
    {
      id: 18,
      Details_of_the_Standard:   "DMM 8 ½",
      Model_and_Make: "3458A, HP",
      Details_Of_the_Traceability: "ETDC(Bg)" ,
      Calibration_date: "04-09-2023",
      Calibration_Due_date: "04-09-2024",
    },
    {
      id: 19,
      Details_of_the_Standard:   "DMM 6 ½",
      Model_and_Make: "34401A, Agilent",
      Details_Of_the_Traceability:  "ETDC(Hyd)",
      Calibration_date: "05-03-2024",
      Calibration_Due_date:"05-03-2025" ,
    },
    {
      id: 20,
      Details_of_the_Standard: "DMM 6 ½",
      Model_and_Make:"7151,Solartron" ,
      Details_Of_the_Traceability:  "ETDC(Hyd)",
      Calibration_date: "05-03-2024",
      Calibration_Due_date: "05-03-2025",
    },
    
    {
        id:21,
        Details_of_the_Standard: "True RMS Multimeter 4½",
        Model_and_Make: "287, Fluke 11210069",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date: "06-02-2024",
        Calibration_Due_date: "06-02-2025",
    },
    {
        id:22,
        Details_of_the_Standard:  "True RMS Multimeter 4½" ,
        Model_and_Make: "287, Fluke 11210083",
        Details_Of_the_Traceability:  "ETDC(Hyd",
        Calibration_date: "06-02-2024",
        Calibration_Due_date: "06-02-2025",
    },
    {
        id:23, 
        Details_of_the_Standard:  "True RMS Multimeter 3½" ,
        Model_and_Make: "177, Fluke",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date: "06-02-2024",
        Calibration_Due_date: "06-02-2025",
    },
    {
        id:24, 
        Details_of_the_Standard:  "Micro wave frequency Counter" ,
        Model_and_Make: "5350B, HP",
        Details_Of_the_Traceability: "ETDC(Bg)" ,
        Calibration_date:"07-11-202" ,
        Calibration_Due_date: "07-11-2024",
      },
      {
        id:25, 
        Details_of_the_Standard: "High Resolution Frequency Counter"  ,
        Model_and_Make: "PM-6668, Philips ",
        Details_Of_the_Traceability:  "ETDC(Hyd)",
        Calibration_date: "04-04-2024",
        Calibration_Due_date: "04-04-2025",     
      },
      {
        id:27, 
        Details_of_the_Standard: "RF POWER Meter with Sensors"  ,
        Model_and_Make: "NRP, R & S" ,
        Details_Of_the_Traceability:  "ETDC(Bg)",
        Calibration_date: "13-11-2023",
        Calibration_Due_date: "13-11-2024",
      },
      {
        id:28,
        Details_of_the_Standard: "--RF Signal Generator"  ,
        Model_and_Make: "SMX, R & S",
        Details_Of_the_Traceability: "ETDC(Bg)" ,
        Calibration_date:"09-11-2023" ,
        Calibration_Due_date:"09-11-2024",
      },
      {
        id: 28,
        Details_of_the_Standard: "--Freq. Doubler"  ,
        Model_and_Make: "11721A,  HP",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date:"21-02-2024" ,
        Calibration_Due_date:"21-02-2025",
      },
      {
        id:29 ,
        Details_of_the_Standard: "High Voltage Probe"  ,
        Model_and_Make: "80K6, Fluke" ,
        Details_Of_the_Traceability: "ETDC(Bg)" ,
        Calibration_date: "21-11-2024",
        Calibration_Due_date: "21-11-2025" ,
      },
      {
        id:30 ,
        Details_of_the_Standard: "High Voltage Probe"  ,
        Model_and_Make: "80K40,  Fluke" ,
        Details_Of_the_Traceability: "ERTL (N)  Mumbai" ,
        Calibration_date: "21-11-2024" ,
        Calibration_Due_date: "21-11-2025",
      },

      {
        id: 31 ,
        Details_of_the_Standard: "Universal Power Analyser",
        Model_and_Make: "PM-3300, Voltech",
        Details_Of_the_Traceability: "ETDC(Bg)",
        Calibration_date: "10-11-2023",
        Calibration_Due_date: "10-11-2024",
  },
  
  
  {
        id: 32,
        Details_of_the_Standard: "Current Transformer" ,
        Model_and_Make: "CT1000 Voltech",
        Details_Of_the_Traceability: "ETDC(Hyd)",
        Calibration_date: "18-11-2024",
        Calibration_Due_date: "18-11-2025",
  },
  
  
  {
        id: 33,
        Details_of_the_Standard: "Digital Clamp Meter" ,
        Model_and_Make: "MX1200S, ITT",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date: "02-04-2024",
        Calibration_Due_date: "02-04-2025",
  },
  
  
  {
        id: 34,
        Details_of_the_Standard:  "DC Shunt" ,
        Model_and_Make: "4638F, Tinsely",
        Details_Of_the_Traceability: "ETDC(Bg)" ,
        Calibration_date: "13-11-2023",
        Calibration_Due_date: "13-11-2024",
  },
  
  
  {
        id: 35,
        Details_of_the_Standard: "Process Calibrator"   ,
        Model_and_Make: "741B, Fluke",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date: "21-02-2024",
        Calibration_Due_date: "21-02-2025",
  },
  
  
  {
        id: 36,
        Details_of_the_Standard: "Thermo Hygro Meter with probe"  ,
        Model_and_Make: "1620 Dewk, Fluke.",
        Details_Of_the_Traceability: "ERTL (N) New Delhi" ,
        Calibration_date: "21-12-2023",
        Calibration_Due_date: "21-12-2024",
  },
  
  
  {
        id: 37,
        Details_of_the_Standard: "RTD Simulator"  ,
        Model_and_Make: "Lab facility",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date: "21-02-2024",
        Calibration_Due_date: "21-02-2025",
  },
  
  
  {
        id: 38,
        Details_of_the_Standard: "Precision RTD Simulator",
        Model_and_Make: "M-612, Meatest",
        Details_Of_the_Traceability: "ETDC (Hyd)" ,
        Calibration_date: "05-03-2024",
        Calibration_Due_date: "05-03-2025",
  },
  
  
  {
        id: 39,
        Details_of_the_Standard: "AC/DC current calibrator",
        Model_and_Make: "M-150S,  Meatest",
        Details_Of_the_Traceability: "ETDC(Hyd)" ,
        Calibration_date: "19-03-2024",
        Calibration_Due_date: "19-03-2025",
  },
  
  
  {
        id: 40,
        Details_of_the_Standard: "DC Shunt-300A",
        Model_and_Make: "Motwane",
        Details_Of_the_Traceability: "ETDC(Bg)",
        Calibration_date: "18-11-2024",
        Calibration_Due_date: "18-11-2025",
  },

    {
      id:41 ,
      Details_of_the_Standard: "DC Shunt-100A"  ,
      Model_and_Make:"Motwane" ,
      Details_Of_the_Traceability:"ETDC(Bg)"  ,
      Calibration_date:"18-11-2024" ,
      Calibration_Due_date:"18-11-2025" ,
    },
    {
      id:42 ,
      Details_of_the_Standard:"High accuracy Decade Resistance Substituter"     ,
      Model_and_Make: "HARS-X2-8-0.01, IET",
      Details_Of_the_Traceability:"ETDC(Hyd)"  ,
      Calibration_date: "05-02-2024",
      Calibration_Due_date: "05-02-2025",
    },
    {
      id:43 ,
      Details_of_the_Standard:"HV-High Resistance Substituter"   ,
      Model_and_Make:"HRRS-Q-5-100M-5KV,IET" ,
      Details_Of_the_Traceability: "ERTL (N) New Delhi" ,
      Calibration_date:"18-11-2024" ,
      Calibration_Due_date: "18-11-2025",
    },
    {
      id: 44,
      Details_of_the_Standard: "Temp. Sensors T/C Type: K "  ,
      Model_and_Make:"RS Comp Qty.:2" ,
      Details_Of_the_Traceability: "ERTL(W) Mumbai" ,
      Calibration_date:"07-12-2023" ,
      Calibration_Due_date:"07-12-2024" ,
    },
    {
      id: 45,
      Details_of_the_Standard: "Temp. Sensors PT-100,"  ,
      Model_and_Make:"Heatek  Controls  Qty:20" ,
      Details_Of_the_Traceability: "ERTL(W) Mumbai" ,
      Calibration_date:"19-01-2024" ,
      Calibration_Due_date:"19-01-2025" ,
    },
    {
      id:46 ,
      Details_of_the_Standard: "Thermo Hygro Meter "  ,
      Model_and_Make: "Zeal (01) (Dry & Wet)",
      Details_Of_the_Traceability:"ETDC(Hyd)"  ,
      Calibration_date: "06-03-2024",
      Calibration_Due_date: "06-03-2025",
    },
    {
      id:47 ,
      Details_of_the_Standard: "Thermo Hygro Meter "  ,
      Model_and_Make:"Zeal (02) (Dry & Wet)" ,
      Details_Of_the_Traceability:"ETDC(Hyd)"  ,
      Calibration_date:"06-03-2024" ,
      Calibration_Due_date: "06-03-2025",
    },
    {
      id:48 ,
      Details_of_the_Standard: "Alaram Hygrometer"  ,
      Model_and_Make:"608-H2,testo" ,
      Details_Of_the_Traceability:"ETDC(Hyd)"  ,
      Calibration_date: "05-03-2024",
      Calibration_Due_date:"05-03-2025" ,
    },
    {
      id:49 ,
      Details_of_the_Standard: "Digital Phosphor Oscilloscope"  ,
      Model_and_Make: "TDS 3052B, B023192",
      Details_Of_the_Traceability:"ETDC(Hyd)"  ,
      Calibration_date: "23-10-2024",
      Calibration_Due_date: "23-10-2025",
    }
    
  ];

  export default items;